### ISSUE TITLE
Merge with rules_haskell?

### ISSUE THREAD

**Issue by zimbatm** [tweag/haskell.build#1]
It would be fairly easy to automate the site publication from the rules_haskell repo to a gh-pages branch.

**Comment by mboes** [comment]
This is already the case. This repository is old. See https://github.com/tweag/rules_haskell/blob/master/heroku.yml. This was done as part of https://github.com/tweag/rules_haskell/pull/129. FTR gh-pages branches are awful. Let's please never do that (not possible to update `master` and the documentation on `gh-pages` atomically).

Updating to the repo description to reflect that.
